import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Pokemon App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className='dark'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className='relative min-h-dvh'>
					<div
						aria-hidden
						className='pointer-events-none fixed inset-0 -z-10'>
						<img
							src='https://nin10dave.com/wp-content/uploads/2020/11/Ho-oh-1024x576.jpg'
							alt=''
							className='h-full w-full object-cover blur-md'
							loading='lazy'
						/>
					</div>
					<div className='relative'>{children}</div>
				</div>
			</body>
		</html>
	);
}
